### ISSUE TITLE
Distinguish Volume For Pause Settings

### ISSUE THREAD

**Issue by zlaw1** [mustachematt/team-b-practicum#15]
Distinguish between music, sound effects, master volume.

**Comment by Kylemc1413** [comment]
Addressed in https://github.com/mustachematt/team-b-practicum/commit/9753a475ed7312bbf2c51cb5c70812305e4a38fe with addition of GameSettings Class that keeps track of the volume setting for master, music, and effects and invokes an action when they are changed, as well as a Volume Control component that can be added to a gameobject with an Audio Source to adjust the volume of the source based on the settings and specified audio type and update the modified volume when the settings are changed.
